kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: resource-pressure-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-pressure
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-pressure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-pressure
      version: v1
  template:
    metadata:
      labels:
        app: resource-pressure
        version: v1
    spec:
      containers:
      - name: resource-pressure
        image: kowlon/preasure:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: NUM_THREADS
          value: "5"
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "300m"
            memory: "1024Mi"
