apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: echo-container
        image: kowlon/go-echo:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "128Mi"
