apiVersion: v1
kind: Pod
metadata:
  name: web-client
spec:
  containers:
  - name: web-client
    image: alpine/curl
    command: [ "sh", "-c", "sleep 3600" ]
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
