apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: simple-task
        image: busybox
        command: ["sh", "-c", "echo Hello, Kubernetes!"]
      restartPolicy: Never