apiVersion: batch/v1
kind: Job
metadata:
  name: ttl-job
spec:
  ttlSecondsAfterFinished: 40 # Job will be deleted 40 seconds after completion
  template:
    spec:
      containers:
      - name: ttl-task
        image: busybox
        command: ["sh", "-c", "echo This job completed; sleep 30"]
      restartPolicy: Never