apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-update-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollback-update-example
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rollback-update-example
    spec:
      containers:
      - name: go-echo
        image: kowlon/go-echo:v4
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
