apiVersion: v1
kind: Pod
metadata:
  name: alpine-secret-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/sh", "-c", "cat /etc/secrets/username; cat /etc/secrets/password" ]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret
