apiVersion: v1
kind: Pod
metadata:
  name: alpine-multi-secret-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/sh", "-c", "cat /etc/secrets/app.properties; cat /etc/secrets/db.properties" ]
    volumeMounts:
    - name: app-secret-volume
      mountPath: /etc/secrets/app.properties
      subPath: app.properties
      readOnly: true
    - name: db-secret-volume
      mountPath: /etc/secrets/db.properties
      subPath: db.properties
  volumes:
  - name: app-secret-volume
    secret:
      secretName: multi-secret
  - name: db-secret-volume
    secret:
      secretName: multi-secret
