apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-retrain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: retrain-storage-class