apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
spec:
  containers:
  - name: alpine-container
    image: alpine
    command: ["sh", "-c", "while true; do sleep 3600; done"]